# Generated by Django 2.2.4 on 2019-08-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
