# Generated by Django 2.2.4 on 2019-08-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_auto_20190824_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
